// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO5lUkrIQDXpIfSflYDb53lHHrJvintso',
    appId: '1:570685183159:web:2e7ce029184f4b05552932',
    messagingSenderId: '570685183159',
    projectId: 'inquire-24d6d',
    authDomain: 'inquire-24d6d.firebaseapp.com',
    databaseURL: 'https://inquire-24d6d-default-rtdb.firebaseio.com',
    storageBucket: 'inquire-24d6d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvABGJlb7uxaxVztJKv1W0iMcHi2LLAAg',
    appId: '1:570685183159:android:5ef796ef66e207ad552932',
    messagingSenderId: '570685183159',
    projectId: 'inquire-24d6d',
    databaseURL: 'https://inquire-24d6d-default-rtdb.firebaseio.com',
    storageBucket: 'inquire-24d6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgYfoSqilJa774QTRntc0EHM7eSZGHkK0',
    appId: '1:570685183159:ios:35474c8513db343a552932',
    messagingSenderId: '570685183159',
    projectId: 'inquire-24d6d',
    databaseURL: 'https://inquire-24d6d-default-rtdb.firebaseio.com',
    storageBucket: 'inquire-24d6d.appspot.com',
    iosBundleId: 'com.example.inquire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgYfoSqilJa774QTRntc0EHM7eSZGHkK0',
    appId: '1:570685183159:ios:078394dbdb39b00d552932',
    messagingSenderId: '570685183159',
    projectId: 'inquire-24d6d',
    databaseURL: 'https://inquire-24d6d-default-rtdb.firebaseio.com',
    storageBucket: 'inquire-24d6d.appspot.com',
    iosBundleId: 'com.example.inquire.RunnerTests',
  );
}
